#!/bin/sh

MODDIR="/lib/modules/$(uname -r)/extra"

case "$1" in
start)
    echo "Loading aesdchar-char-driver module"
    # aesdchar_load expects to be run from the directory containing the .ko file
    (cd $MODDIR && /usr/bin/aesdchar_load)
    ;;
stop)
    echo "Unloading aesdchar-char-driver module"
    /usr/bin/aesdchar_unload
    ;;
*)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
